"""Parsers for Grok-specific file formats (SKILL.md frontmatter, etc)."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml


FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


@dataclass
class Skill:
    name: str
    description: str
    path: Path
    scope: str = "user"
    content: str = ""
    frontmatter: dict[str, Any] = field(default_factory=dict)

    @property
    def is_valid(self) -> bool:
        return bool(self.name and self.description)


def parse_skill(skill_dir: Path, scope: str = "user") -> Optional[Skill]:
    """Parse a skill directory. Returns None if no/invalid SKILL.md."""
    md = skill_dir / "SKILL.md"
    if not md.exists():
        return None
    try:
        text = md.read_text(encoding="utf-8")
    except Exception:
        return None

    fm: dict[str, Any] = {}
    body = text
    m = FRONTMATTER_RE.search(text)
    if m:
        try:
            fm = yaml.safe_load(m.group(1)) or {}
            body = text[m.end() :]
        except Exception:
            fm = {}

    name = fm.get("name") or skill_dir.name
    desc = fm.get("description") or (body.strip().split("\n\n")[0][:200] if body.strip() else "")

    return Skill(
        name=str(name).strip().lower(),
        description=str(desc).strip(),
        path=skill_dir,
        scope=scope,
        content=body.strip(),
        frontmatter=fm,
    )


def iter_skills(grok_home: Path) -> list[Skill]:
    """Discover and parse all skills from known locations (higher prio first, dedup names)."""
    from .common import get_skills_dirs

    seen: set[str] = set()
    results: list[Skill] = []
    for scope, sdir in get_skills_dirs(grok_home):
        if not sdir or not sdir.exists():
            continue
        for child in sorted(sdir.iterdir()):
            if not child.is_dir():
                continue
            skill = parse_skill(child, scope=scope)
            if skill and skill.name not in seen:
                seen.add(skill.name)
                results.append(skill)
    return results


def validate_skill(skill: Skill) -> list[str]:
    """Return list of validation error messages (empty = valid)."""
    errs: list[str] = []
    if not skill.name or len(skill.name) > 64:
        errs.append("name must be 1-64 chars, lowercase with hyphens ok")
    if not skill.description or len(skill.description) < 10:
        errs.append("description must be at least 10 chars (used for auto-invocation)")
    if "name" not in skill.frontmatter:
        errs.append("frontmatter missing required 'name'")
    if "description" not in skill.frontmatter:
        errs.append("frontmatter missing required 'description'")
    # check for basic steps or content
    if len(skill.content) < 30:
        errs.append("SKILL.md body looks very short; add steps/instructions")
    return errs


def skill_template(name: str, description: str) -> str:
    """Generate a high-quality starter SKILL.md."""
    slug = name.lower().replace(" ", "-").replace("_", "-")
    return f"""---
name: {slug}
description: {description}
---

# {name.title()}

{description}

## When to use

- Trigger phrase 1...
- Trigger phrase 2...

## Steps

1. ...
2. Run the appropriate command/tool
3. Verify output and summarize for the user

## Best Practices

- Always ...
- Never ...
- Prefer ...

## Examples

```bash
# example invocation
```

## Notes

- This skill was generated by grok-utils skills create
"""
